language: php
php:
- 5.5
env:
- TRAVIS_NODE_VERSION="0.12"
sudo: false
before_script:
- travis_retry composer self-update
- travis_retry composer install --prefer-source --no-interaction
- touch storage/app/database.sqlite
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION
- npm install
- gulp --production
script:
- phpunit
notifications:
  email: false
  webhooks:
    on_success: always
    on_failure: never